/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'productId' : IDL.Nat32,
  'quantity' : IDL.Nat32,
});
export const Cart = IDL.Vec(CartItem);
export const ShippingInfo = IDL.Record({
  'zip' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat32,
  'paymentCardLast4' : IDL.Nat32,
  'cart' : IDL.Vec(CartItem),
  'totalPriceCents' : IDL.Nat32,
  'shippingInfo' : ShippingInfo,
});
export const Product = IDL.Record({
  'id' : IDL.Nat32,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceCents' : IDL.Nat32,
});

export const idlService = IDL.Service({
  'addItemToCart' : IDL.Func([IDL.Text, IDL.Nat32, IDL.Nat32], [], []),
  'clearCart' : IDL.Func([IDL.Text], [], []),
  'getCart' : IDL.Func([IDL.Text], [Cart], ['query']),
  'getOrder' : IDL.Func([IDL.Nat32], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat32], [IDL.Opt(Product)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, ShippingInfo, IDL.Nat32], [IDL.Nat32], []),
  'removeItemFromCart' : IDL.Func([IDL.Text, IDL.Nat32], [], []),
  'updateCartItem' : IDL.Func([IDL.Text, IDL.Nat32, IDL.Nat32], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({
    'productId' : IDL.Nat32,
    'quantity' : IDL.Nat32,
  });
  const Cart = IDL.Vec(CartItem);
  const ShippingInfo = IDL.Record({
    'zip' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat32,
    'paymentCardLast4' : IDL.Nat32,
    'cart' : IDL.Vec(CartItem),
    'totalPriceCents' : IDL.Nat32,
    'shippingInfo' : ShippingInfo,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat32,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceCents' : IDL.Nat32,
  });
  
  return IDL.Service({
    'addItemToCart' : IDL.Func([IDL.Text, IDL.Nat32, IDL.Nat32], [], []),
    'clearCart' : IDL.Func([IDL.Text], [], []),
    'getCart' : IDL.Func([IDL.Text], [Cart], ['query']),
    'getOrder' : IDL.Func([IDL.Nat32], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat32], [IDL.Opt(Product)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, ShippingInfo, IDL.Nat32],
        [IDL.Nat32],
        [],
      ),
    'removeItemFromCart' : IDL.Func([IDL.Text, IDL.Nat32], [], []),
    'updateCartItem' : IDL.Func([IDL.Text, IDL.Nat32, IDL.Nat32], [], []),
  });
};

export const init = ({ IDL }) => { return []; };