/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Cart = Array<CartItem>;
export interface CartItem { 'productId' : number, 'quantity' : number }
export interface Order {
  'id' : number,
  'paymentCardLast4' : number,
  'cart' : Array<CartItem>,
  'totalPriceCents' : number,
  'shippingInfo' : ShippingInfo,
}
export interface Product {
  'id' : number,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'priceCents' : number,
}
export interface ShippingInfo {
  'zip' : string,
  'country' : string,
  'city' : string,
  'name' : string,
  'email' : string,
  'address' : string,
}
export interface _SERVICE {
  'addItemToCart' : ActorMethod<[string, number, number], undefined>,
  'clearCart' : ActorMethod<[string], undefined>,
  'getCart' : ActorMethod<[string], Cart>,
  'getOrder' : ActorMethod<[number], [] | [Order]>,
  'getProduct' : ActorMethod<[number], [] | [Product]>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[string, ShippingInfo, number], number>,
  'removeItemFromCart' : ActorMethod<[string, number], undefined>,
  'updateCartItem' : ActorMethod<[string, number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];